//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 08:06:15 AM EDT 
//


package ca.twokeys.xml.pskc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ca.twokeys.xml.xenc.EncryptedDataType;


/**
 * <p>Java class for binaryDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="binaryDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PlainValue" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *           &lt;element name="EncryptedValue" type="{http://www.w3.org/2001/04/xmlenc#}EncryptedDataType"/>
 *         &lt;/choice>
 *         &lt;element name="ValueMAC" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "binaryDataType", propOrder = {
    "plainValue",
    "encryptedValue",
    "valueMAC"
})
public class BinaryDataType {

    @XmlElement(name = "PlainValue")
    protected byte[] plainValue;
    @XmlElement(name = "EncryptedValue")
    protected EncryptedDataType encryptedValue;
    @XmlElement(name = "ValueMAC")
    protected byte[] valueMAC;

    /**
     * Gets the value of the plainValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPlainValue() {
        return plainValue;
    }

    /**
     * Sets the value of the plainValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPlainValue(byte[] value) {
        this.plainValue = value;
    }

    /**
     * Gets the value of the encryptedValue property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedDataType }
     *     
     */
    public EncryptedDataType getEncryptedValue() {
        return encryptedValue;
    }

    /**
     * Sets the value of the encryptedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedDataType }
     *     
     */
    public void setEncryptedValue(EncryptedDataType value) {
        this.encryptedValue = value;
    }

    /**
     * Gets the value of the valueMAC property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getValueMAC() {
        return valueMAC;
    }

    /**
     * Sets the value of the valueMAC property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setValueMAC(byte[] value) {
        this.valueMAC = value;
    }

}
