//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 08:03:14 AM EDT 
//


package ca.twokeys.xml.pkcs5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.twokeys.tv.xml.pkcs5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PBKDF2Params_QNAME = new QName("http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", "PBKDF2-params");
    private final static QName _PBES2Params_QNAME = new QName("http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", "PBES2-params");
    private final static QName _PBMAC1Params_QNAME = new QName("http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", "PBMAC1-params");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.twokeys.tv.xml.pkcs5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PBKDF2ParameterType }
     * 
     */
    public PBKDF2ParameterType createPBKDF2ParameterType() {
        return new PBKDF2ParameterType();
    }

    /**
     * Create an instance of {@link PBES2ParameterType }
     * 
     */
    public PBES2ParameterType createPBES2ParameterType() {
        return new PBES2ParameterType();
    }

    /**
     * Create an instance of {@link PBMAC1ParameterType }
     * 
     */
    public PBMAC1ParameterType createPBMAC1ParameterType() {
        return new PBMAC1ParameterType();
    }

    /**
     * Create an instance of {@link SaltAlgorithmIdentifierType }
     * 
     */
    public SaltAlgorithmIdentifierType createSaltAlgorithmIdentifierType() {
        return new SaltAlgorithmIdentifierType();
    }

    /**
     * Create an instance of {@link PRFAlgorithmIdentifierType }
     * 
     */
    public PRFAlgorithmIdentifierType createPRFAlgorithmIdentifierType() {
        return new PRFAlgorithmIdentifierType();
    }

    /**
     * Create an instance of {@link AlgorithmIdentifierType }
     * 
     */
    public AlgorithmIdentifierType createAlgorithmIdentifierType() {
        return new AlgorithmIdentifierType();
    }

    /**
     * Create an instance of {@link PBKDF2ParameterType.Salt }
     * 
     */
    public PBKDF2ParameterType.Salt createPBKDF2ParameterTypeSalt() {
        return new PBKDF2ParameterType.Salt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PBKDF2ParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", name = "PBKDF2-params")
    public JAXBElement<PBKDF2ParameterType> createPBKDF2Params(PBKDF2ParameterType value) {
        return new JAXBElement<PBKDF2ParameterType>(_PBKDF2Params_QNAME, PBKDF2ParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PBES2ParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", name = "PBES2-params")
    public JAXBElement<PBES2ParameterType> createPBES2Params(PBES2ParameterType value) {
        return new JAXBElement<PBES2ParameterType>(_PBES2Params_QNAME, PBES2ParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PBMAC1ParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#", name = "PBMAC1-params")
    public JAXBElement<PBMAC1ParameterType> createPBMAC1Params(PBMAC1ParameterType value) {
        return new JAXBElement<PBMAC1ParameterType>(_PBMAC1Params_QNAME, PBMAC1ParameterType.class, null, value);
    }

}
