//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 08:03:14 AM EDT 
//


package ca.twokeys.xml.pkcs5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ca.twokeys.xml.xenc.EncryptionMethodType;


/**
 * <p>Java class for PBES2ParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PBES2ParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyDerivationFunc" type="{http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#}AlgorithmIdentifierType"/>
 *         &lt;element name="EncryptionScheme" type="{http://www.w3.org/2001/04/xmlenc#}EncryptionMethodType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PBES2ParameterType", propOrder = {
    "keyDerivationFunc",
    "encryptionScheme"
})
public class PBES2ParameterType {

    @XmlElement(name = "KeyDerivationFunc", required = true)
    protected AlgorithmIdentifierType keyDerivationFunc;
    @XmlElement(name = "EncryptionScheme", required = true)
    protected EncryptionMethodType encryptionScheme;

    /**
     * Gets the value of the keyDerivationFunc property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmIdentifierType }
     *     
     */
    public AlgorithmIdentifierType getKeyDerivationFunc() {
        return keyDerivationFunc;
    }

    /**
     * Sets the value of the keyDerivationFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmIdentifierType }
     *     
     */
    public void setKeyDerivationFunc(AlgorithmIdentifierType value) {
        this.keyDerivationFunc = value;
    }

    /**
     * Gets the value of the encryptionScheme property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptionMethodType }
     *     
     */
    public EncryptionMethodType getEncryptionScheme() {
        return encryptionScheme;
    }

    /**
     * Sets the value of the encryptionScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptionMethodType }
     *     
     */
    public void setEncryptionScheme(EncryptionMethodType value) {
        this.encryptionScheme = value;
    }

}
