//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 08:03:14 AM EDT 
//


package ca.twokeys.xml.pkcs5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRFAlgorithmIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRFAlgorithmIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.rsasecurity.com/rsalabs/pkcs/schemas/pkcs-5v2-0#}AlgorithmIdentifierType">
 *       &lt;attribute name="Algorithm" type="{http://www.w3.org/2001/XMLSchema}anyURI" default="http://www.w3.org/2000/09/xmldsig#hmac-sha1http://www.w3c.org/hmac-sha1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRFAlgorithmIdentifierType")
public class PRFAlgorithmIdentifierType
    extends AlgorithmIdentifierType
{


}
